"""add discount and discount_amount to perfume

Revision ID: 4fcb559c909c
Revises: 5c2f919ac8ca
Create Date: 2026-07-25 12:42:39.226164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fcb559c909c'
down_revision = '5c2f919ac8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfume', schema=None) as batch_op:
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('discount')

    # ### end Alembic commands ###
