"""add image_url

Revision ID: 7a039c8a59fb
Revises: 9ff2c377e0eb
Create Date: 2026-07-09 23:36:44.888528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a039c8a59fb'
down_revision = '9ff2c377e0eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
