"""add category

Revision ID: 9ff2c377e0eb
Revises: 02eb32272597
Create Date: 2026-07-07 20:27:35.814188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff2c377e0eb'
down_revision = '02eb32272597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfume', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
