"""make units nullable

Revision ID: c9f25b12f9dd
Revises: 4fcb559c909c
Create Date: 2026-07-26 09:07:19.532424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f25b12f9dd'
down_revision = '4fcb559c909c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfume', schema=None) as batch_op:
        batch_op.alter_column('units',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfume', schema=None) as batch_op:
        batch_op.alter_column('units',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
